Description: Provisioning Lambda Function and S3 Bucket
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: proxy-96-bucket
  SimpleLambdaFunction:
        Type: AWS::Lambda::Function
        Properties:
          Architectures: 
            - x86_64
          Handler: index.handler
          Role: arn:aws:iam::770630113975:role/proxy-lambda-fn
          Code:
            ZipFile: |
              console.log('Loading function');

              exports.handler = async (event, context) => {
              //console.log('Received event:', JSON.stringify(event, null, 2));
              console.log('value1 =', event.key1);
              console.log('value2 =', event.key2);
              console.log('value3 =', event.key3);
              return event.key1;  // Echo back the first key value
              // throw new Error('Something went wrong');
              };
          Runtime: nodejs12.x
          Timeout: 25
          TracingConfig:
            Mode: Active